-- Table Structure Overview

EXEC sp_help 'accounts';
EXEC sp_help 'products';
EXEC sp_help 'sales_teams';
EXEC sp_help 'sales_pipeline';

-- QUESTIONS

-- Sales Pipeline Overview and Deal Distribution

-- 1. Show the total number of deals in each deal stage.

SELECT deal_stage, COUNT(deal_stage) AS No_of_deals 
FROM sales_pipeline
GROUP BY deal_stage;

-- 2. Find the total deal value for each deal stage.

SELECT deal_stage, SUM(COALESCE(close_value,0)) AS 'total_deal_value' 
FROM sales_pipeline
GROUP BY deal_stage;

-- 3. Show the number of deals handled by each sales agent.

SELECT sales_agent, COUNT(deal_stage) AS No_of_deals 
FROM sales_pipeline
GROUP BY sales_agent;

-- 4. Display sales agents who have handled more than 350 deals in descending order.

SELECT sales_agent, COUNT(deal_stage) AS No_of_deals 
FROM sales_pipeline
GROUP BY sales_agent
HAVING COUNT(deal_stage)>350
ORDER BY No_of_deals DESC;

-- Sales Agent Performance Analysis

-- 5. List the top 5 sales agents by total revenue from “Won” deals.

SELECT TOP 5 sales_agent, SUM(COALESCE(close_value,0)) AS total_revenue 
FROM sales_pipeline
WHERE deal_stage = 'Won'
GROUP BY sales_agent
ORDER BY total_revenue DESC;

-- 6. Retrieve distinct industries (sectors) along with the number of companies in each sector.

SELECT sector, COUNT(account) AS No_of_companies 
FROM accounts
GROUP BY sector 
ORDER BY No_of_companies DESC;

-- 7. Find the 5 most recent closed deals with their deal value and the name of the sales agent.

SELECT TOP 5 close_date,sales_agent, close_value 
FROM sales_pipeline
WHERE close_date is	NOT NULL
ORDER BY close_value DESC

-- 8. Display sales agents who have closed at least one deal.

SELECT DISTINCT sales_agent 
FROM sales_pipeline
where close_value >= 1;

-- Revenue & Product Performance

-- 9. Calculate total revenue generated by each product series.

SELECT p.series, SUM(sp.close_value) AS total_revenue FROM products p
LEFT JOIN sales_pipeline sp
ON sp.product = p.product
WHERE close_value IS NOT NULL
GROUP BY series;

-- 10. Calculate total revenue generated by each industry (sector) and product series.

SELECT a.sector, p.series, SUM(sp.close_value) AS total_revenue FROM accounts a
INNER JOIN sales_pipeline sp
ON a.account = sp.account
INNER JOIN products p
ON p.product = sp.product
WHERE sp.deal_stage = 'Won'
GROUP BY a.sector, p.series
ORDER BY total_revenue DESC;

-- Industry & Regional Insight

-- 11. Show total revenue generated by each regional office.

SELECT s.regional_office, SUM(sp.close_value) AS total_revenue FROM sales_teams s
INNER JOIN sales_pipeline sp
ON s.sales_agent = sp.sales_agent
WHERE sp.deal_stage = 'Won'
GROUP BY s.regional_office;

-- 12. Identify the top 3 accounts by total revenue, along with their industry and assigned sales manager.

SELECT TOP 3 a.account, a.sector, s.manager, SUM(sp.close_value) AS total_revenue 
FROM accounts a
LEFT JOIN sales_pipeline sp
ON a.account = sp.account
LEFT JOIN sales_teams s
ON s.sales_agent = sp.sales_agent
WHERE sp.deal_stage = 'Won'
GROUP BY a.account, a.sector, s.manager
ORDER BY total_revenue DESC;

-- 13. Count the number of deals Won by each office location within first 15 days of March.

SELECT a.office_location, COUNT(sp.deal_stage) AS deals_won FROM accounts a
INNER JOIN sales_pipeline sp
ON a.account = sp.account
WHERE sp.deal_stage = 'Won'
AND sp.close_date BETWEEN '2017-04-01' AND '2017-04-15'
GROUP BY a.office_location
ORDER BY deals_won DESC;

-- Advanced Analytics & Benchmarking 

-- 14. Show the top 10 sales agents along with their total revenue and revenue rank.

WITH x AS 
(SELECT sales_agent, SUM(close_value) AS total_revenue,
RANK() OVER (ORDER BY SUM(close_value) DESC) AS revenue_rank
FROM sales_pipeline
WHERE deal_stage = 'Won'
GROUP BY sales_agent)
SELECT sales_agent, total_revenue, revenue_rank FROM x
WHERE revenue_rank <= 10;

-- 15. Find products whose average deal value is higher than the overall average.

SELECT product, AVG(close_value) AS avg_deal_value FROM sales_pipeline
WHERE deal_stage = 'Won'
GROUP BY product
HAVING AVG(close_value) > (SELECT AVG(close_value) FROM sales_pipeline);

-- 16. List sales agents who closed deals worth more than the average closed deal value.

SELECT DISTINCT sales_agent FROM sales_pipeline
WHERE deal_stage = 'Won' AND 
close_value > (SELECT AVG(close_value) FROM sales_pipeline
WHERE deal_stage = 'Won');